### ISSUE TITLE
feedback cont education session

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-python-training#6]

**Comment by luisesanmartin** [comment]
> 
> 
> When you got the error in `for element in list` when list name was `list1` you got error. This made me think that we should have a slide with some carefully selected error that we can show how to interpret

@kbjarkefur I won't be adding a slide on this for #7 but this is listed in the ideas for an Intro II session on #8

**Comment by weilu** [comment]
> We might have to spend more time giving motivations for why we cover the data types. People want to know how they run regressions, how they create data sets etc. But all of those use these building blocks and if you do not understand the building blocks you will not be able to interact with the data types for data sets and regressions as they use the same building blocks

If it's on the roadmap to eventually have a session on how to run regressions & producing publication quality tables using python this could be great starting point material: https://maxghenis.github.io/pythonomics/intro.html
